rule_files:
  - disk.yml
evaluation_interval: 1m
tests:
  - interval: 1m
    input_series:
      # 从 100GB 每分钟掉 1GB，共 60 个点（覆盖 1h 窗口）
      - series: 'node_filesystem_free_bytes{mountpoint="/"}'
        values: '100000000000-1000000000x59'
    alert_rule_test:
      # 期望：5m for 之后触发
      - eval_time: 10m
        alertname: DiskWillFillIn6h
        exp_alerts:
          - exp_labels:
              severity: warning
              mountpoint: "/"
            exp_annotations:
              summary: "disk will fill in 6h"
