global:
  scrape_interval: 2s
  external_labels:
    cluster: l7-backend
    role: longterm

scrape_configs:
  - job_name: l7-app-from-backend
    static_configs:
      - targets: ["l7-app:8080"]
  - job_name: backend-self
    static_configs:
      - targets: ["localhost:9090"]
