#!/bin/bash
# 课 12 步骤 3：知识点 3 —— 典型场景架构与反模式
# 用法：bash lesson12-step3.sh
#
# 核心：把前两个知识点的实测证据，落到「什么场景该怎么搭」和「什么坑不能踩」。

FE='docker exec -i doris-learn mysql -h 127.0.0.1 -P 9030 -uroot shop'
q() { $FE -e "$1" 2>&1 | grep -vE "^Warning|Using a password"; }
t() {
  START=$(date +%s.%N)
  $FE -e "$1" > /dev/null 2>&1
  END=$(date +%s.%N)
  echo "$(echo "$END - $START" | bc)"
}

echo "################################################################"
echo "# 3.1 典型场景 1：实时数仓（Doris 的主场）"
echo "################################################################"
echo ""
echo "  架构：业务库 --CDC--> Kafka --Routine Load--> Doris <-- 报表/BI"
echo "  本机就有一套：doris-kafka 容器 + kafka_orders 表（课 6 建的）"
echo ""
q "SHOW ROUTINE LOAD\G" | grep -E "^ +(Name|State|TableName):" | head -12
echo ""
echo "  ↑ 没有输出说明当前没跑着的 Routine Load（课 6 结束后停了）"
echo "    这不影响理解架构，关键是链路形态："
echo "      MySQL binlog → Kafka → Doris Routine Load → 秒级可见"
echo ""
echo "  Doris 在这个场景的三个优势（前 11 课都验证过）："
echo "    ① Unique Key 支持 UPSERT，天然吃 CDC 的更新流（课 3）"
echo "    ② 物化视图 / Rollup 预聚合，报表查询快（课 8）"
echo "    ③ 资源隔离让导入和查询互不干扰（课 10）"

echo ""
echo "################################################################"
echo "# 3.2 典型场景 2：日志分析（抢 ES 的场景，但有前提）"
echo "################################################################"
echo ""
echo "  架构：应用日志 --Filebeat--> Kafka --> Doris（倒排索引）<-- 检索"
echo ""
echo "  本机实测的倒排索引（20 万行）："
q "SELECT COUNT(*) AS error_cnt FROM log_search WHERE level MATCH 'ERROR';"
q "SELECT COUNT(*) AS total FROM log_search;"
echo ""
echo "  Doris 相对 ES 的优势："
echo "    - 一份数据既能检索又能聚合（ES 做聚合要额外建索引或导出）"
echo "    - 存储成本低（列存压缩率高）"
echo "    - SQL 接口，不用学 DSL"
echo ""
echo "  但有两个前提（本机实测踩到）："
echo "    ⚠️ ① 中文分词要装 jieba 字典（step1 实测报错）"
echo "    ⚠️ ② 短语检索 MATCH_PHRASE 要求 term 严格相邻（step1 实测返回空）"
echo ""
echo "  什么时候仍该选 ES："
echo "    - 需要复杂的相关性打分（BM25 调优、自定义评分）"
echo "    - 需要高亮、聚合桶嵌套等 ES 生态能力"
echo "    - 日志量极大且以全文检索为主、几乎不做数值聚合"

echo ""
echo "################################################################"
echo "# 3.3 典型场景 3：湖仓加速（Hive/Spark 的补充，不是替代）"
echo "################################################################"
echo ""
echo "  架构：数据湖（Iceberg/Hudi/Hive）--> Doris 外表查询 / 导入加速 <-- BI"
echo ""
echo "  本机没有 Hive，但可以用 S3 TVF 演示「直接查湖上文件」这条链路："
echo ""
q "SELECT province, SUM(amount) AS s FROM S3(
     'uri' = 'http://minio:9000/doris-demo/l12/*',
     's3.access_key' = 'minioadmin', 's3.secret_key' = 'minioadmin',
     's3.region' = 'us-east-1', 'use_path_style' = 'true', 'format' = 'parquet')
   GROUP BY province ORDER BY s DESC LIMIT 5;"
echo ""
echo "  → 这就是「湖仓加速」的雏形：不改数据位置，直接查。"
echo "    生产上用 Catalog 功能对接 Hive Metastore / Iceberg："
echo "      CREATE CATALOG hive PROPERTIES('type'='hms', 'hive.metastore.uris'='...');"
echo "    🔴 本机无 Hive Metastore，此语句未实测"
echo ""
echo "  分工建议："
echo "    - 湖负责：廉价存历史全量、批处理 ETL、数据回溯"
echo "    - Doris 负责：热数据交互式查询、加速层"
echo "    - 不要拿 Doris 当数据湖用（存储成本不划算）"

echo ""
echo "################################################################"
echo "# 3.4 反模式 1：拿 Doris 当 KV 缓存用"
echo "################################################################"
echo ""
echo "  症状：高频单行点查（按主键查单条），QPS 要求上千"
echo ""
IDS=$($FE -N -e "SELECT GROUP_CONCAT(id) FROM (SELECT id FROM anti_kv ORDER BY id LIMIT 200) t;" 2>/dev/null)
S=$(date +%s.%N)
{
  for id in $(echo "$IDS" | tr ',' ' '); do
    echo "SELECT id, amount FROM anti_kv WHERE id = $id;"
  done
} | docker exec -i doris-learn mysql -h 127.0.0.1 -P 9030 -uroot shop -N > /tmp/l12_p3.out 2>&1
E=$(date +%s.%N)
PT=$(echo "$E - $S" | bc)
echo "  实测：单连接串行 200 次点查 = ${PT} 秒"
echo "        单次约 $(echo "scale=2; $PT * 1000 / 200" | bc) ms"
echo "        吞吐约 $(echo "scale=0; 200 / $PT" | bc) QPS（单连接，未并发）"
echo ""
echo "  问题："
echo "    ① 5-7 ms 延迟对 KV 场景是灾难（Redis 约 0.1 ms，差 50 倍以上）"
echo "    ② 每次查询都要走完整的查询规划、调度、扫描流程"
echo "    ③ 吞吐型引擎做延迟型的事，资源利用率极低"
echo ""
echo "  正确做法：Redis / HBase 做点查，Doris 做分析，各干各的"

echo ""
echo "################################################################"
echo "# 3.5 反模式 2：拿 Doris 当 OLTP 库用（依赖事务）"
echo "################################################################"
echo ""
echo "  症状：业务代码里写 BEGIN / ROLLBACK，指望多语句原子性"
echo ""
q "DROP TABLE IF EXISTS anti_txn2;"
q "CREATE TABLE anti_txn2 (
     id BIGINT NOT NULL, amount DECIMAL(18,2) NULL, memo VARCHAR(64) NULL
   ) UNIQUE KEY(id) DISTRIBUTED BY HASH(id) BUCKETS 2
   PROPERTIES ('replication_num' = '1', 'enable_unique_key_merge_on_write' = 'true');"
q "INSERT INTO anti_txn2 VALUES (1, 100.00, 'init');"
echo ""
echo "  模拟转账：A 扣 30，B 加 30，中间出错要整体回滚"
q "BEGIN;"
q "UPDATE anti_txn2 SET amount = amount - 30 WHERE id = 1;"
q "INSERT INTO anti_txn2 VALUES (2, 30.00, 'from_1');"
q "ROLLBACK;"
echo ""
echo "  ROLLBACK 之后，看看数据成什么样了："
q "SELECT id, amount, memo FROM anti_txn2 ORDER BY id;"
echo ""
echo "  ⚠️ 钱扣了、账也加了，ROLLBACK 什么都没撤。"
echo "     Doris 的 BEGIN/COMMIT/ROLLBACK 是 MySQL 协议兼容，"
echo "     不提供跨语句原子性 —— 每条 DML 自己是一个原子单元。"
echo ""
echo "  正确做法："
echo "    - 需要事务的业务逻辑放 MySQL/PG，Doris 只做分析副本"
echo "    - 或用 Doris 单条 UPSERT 的原子性（Unique Key 单行写入是原子的）"
q "DROP TABLE IF EXISTS anti_txn2;"

echo ""
echo "################################################################"
echo "# 3.6 反模式 3：高频单行 UPDATE / DELETE"
echo "################################################################"
echo ""
echo "  症状：每分钟成千上万次单行 UPDATE，把 Doris 当业务库写"
echo ""
echo "  为什么慢（课 9 讲过 compaction，这里串起来）："
echo "    ① Doris 的 UPDATE/DELETE 是标记删除（delete predicate）"
echo "    ② 每次查询都要额外过滤这些标记，越积越多越慢"
echo "    ③ 靠后台 compaction 合并清理，但高频写入会让 compaction 跟不上"
echo ""
echo "  本机实测：单行 UPDATE 能执行，但代价隐藏在后续查询里"
q "SELECT COUNT(*) AS cnt FROM anti_kv;"
echo ""
echo "  正确做法："
echo "    - 批量 UPDATE（攒批，一次改几千几万行）"
echo "    - 或用 Unique Key 的 UPSERT 整行覆盖（课 3 讲过）"
echo "    - 或按分区整体替换（ALTER TABLE ... REPLACE PARTITION）"

echo ""
echo "################################################################"
echo "# 3.7 反模式 4：不建分区 / 分区粒度选错"
echo "################################################################"
echo ""
echo "  症状：几亿行的大表不分区，或按高基数列分区"
echo ""
echo "  本机 orders 表就是个反面例子（课 2 建的，单分区 2150 万行）："
q "SHOW PARTITIONS FROM orders;" | awk -F'\t' 'NR==1{for(i=1;i<=NF;i++){if($i=="PartitionName")p=i;if($i=="RowCount")r=i};next}{printf "     分区=%-12s 行数=%s\n",$p,$r}'
echo ""
echo "  问题："
echo "    ① 不分区 → 没法按时间淘汰数据，只能 DELETE（触发反模式 3）"
echo "    ② 按高基数列分区（如 user_id）→ 分区数爆炸，元数据压力巨大"
echo ""
echo "  正确做法："
echo "    - 按时间分区（天/月），既能裁剪查询，又能整分区 DROP 淘汰"
echo "    - 分桶按高频 JOIN/GROUP BY 列（课 9 讲过 Colocate Join）"

echo ""
echo "################################################################"
echo "# 3.8 反模式 5：把宽表当万能解（滥用大宽表）"
echo "################################################################"
echo ""
echo "  症状：为了「一次查询搞定」，把几十张表 JOIN 成一张几百列的大宽表"
echo ""
echo "  实测：宽表扫描的代价（step1 已测）"
echo "    扫 1 列：0.13-0.14 秒"
echo "    扫 13 列：0.51-0.60 秒"
echo "    → 列数翻 13 倍，耗时翻 4 倍"
echo ""
echo "  问题："
echo "    ① 列存虽只读需要的列，但宽表会让 Schema Change 变重（课 11）"
echo "    ② 数据冗余，上游一改就要全表重刷"
echo "    ③ 稀疏列（大部分为 NULL）浪费字典编码"
echo ""
echo "  正确做法："
echo "    - 星型模型：事实表 + 维度表，用 Colocate Join（课 9）"
echo "    - 或适度冗余高频维度和低基数列，不是无脑全冗余"

echo ""
echo "################################################################"
echo "# 3.9 决策清单：到底该不该用 Doris"
echo "################################################################"
echo ""
echo "  ✅ 该用的信号："
echo "    - 数据量在 TB 级，查询以聚合/分组为主"
echo "    - 需要亚秒级到秒级的交互式分析响应"
echo "    - 查询模式相对固定，可以靠物化视图/索引优化"
echo "    - 需要 SQL 接口，团队熟悉 MySQL 生态"
echo "    - 既要实时导入，又要实时查询"
echo ""
echo "  ❌ 不该用的信号："
echo "    - 高频单行点查（KV 场景）→ 用 Redis / HBase"
echo "    - 依赖多语句事务（OLTP）→ 用 MySQL / PG"
echo "    - 复杂全文检索与相关性打分 → 用 ES"
echo "    - 单纯存冷数据、几乎不查 → 用对象存储 / 数据湖"
echo "    - 数据量只有几 GB → 用 MySQL 就够了，别引入分布式复杂度"
echo ""
echo "  下一步：bash lesson12-cleanup.sh"
