# Generated by Django 6.1 on 2026-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单 ID')),
                ('notify_ok', models.BooleanField(default=False, verbose_name='通知是否成功')),
                ('coupon_ok', models.BooleanField(default=False, verbose_name='发券是否成功')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'orders_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='商品 SKU')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
            ],
            options={
                'db_table': 'orders_stock',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户 ID')),
                ('sku', models.CharField(max_length=64, verbose_name='商品 SKU')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('status', models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('CLOSED', '已关闭')], default='PENDING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('fulfillment_task_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='履约任务 ID')),
            ],
            options={
                'db_table': 'orders_order',
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_status_created'), models.Index(fields=['user_id', 'created_at'], name='idx_user_created')],
            },
        ),
    ]
