-- 订单系统的最小生产化数据模型。
-- 对应课程：阶段 1/2（类型、约束、关系、视图、函数、触发器、CTE、窗口函数）。

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE SCHEMA orders AUTHORIZATION postgres;

CREATE TABLE orders.tenants (
    tenant_id uuid PRIMARY KEY,
    tenant_name text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE orders.product_categories (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES orders.tenants(tenant_id),
    parent_category_id bigint REFERENCES orders.product_categories(category_id),
    category_name text NOT NULL,
    UNIQUE (tenant_id, category_name)
);

CREATE TABLE orders.customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES orders.tenants(tenant_id),
    email text NOT NULL,
    display_name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, email)
);

CREATE TABLE orders.products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES orders.tenants(tenant_id),
    category_id bigint REFERENCES orders.product_categories(category_id),
    sku text NOT NULL,
    product_name text NOT NULL,
    price numeric(12, 2) NOT NULL CHECK (price > 0),
    stock integer NOT NULL CHECK (stock >= 0),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, sku)
);

CREATE TABLE orders.orders (
    order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES orders.tenants(tenant_id),
    customer_id bigint NOT NULL REFERENCES orders.customers(customer_id),
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled')),
    total_amount numeric(14, 2) NOT NULL CHECK (total_amount >= 0),
    idempotency_key text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE orders.order_items (
    order_id bigint NOT NULL REFERENCES orders.orders(order_id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES orders.products(product_id),
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12, 2) NOT NULL CHECK (unit_price > 0),
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE orders.order_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders.orders(order_id) ON DELETE CASCADE,
    event_type text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- 读路径：等值租户 + 时间范围是订单列表的主访问模式。
CREATE INDEX orders_orders_tenant_created_idx
    ON orders.orders (tenant_id, created_at DESC, order_id DESC)
    INCLUDE (status, total_amount);
CREATE INDEX orders_orders_pending_idx
    ON orders.orders (tenant_id, created_at DESC)
    WHERE status = 'pending';
CREATE INDEX orders_order_items_product_idx
    ON orders.order_items (product_id);
CREATE INDEX orders_products_metadata_gin_idx
    ON orders.products USING gin (metadata);
CREATE INDEX orders_orders_created_brin_idx
    ON orders.orders USING brin (created_at) WITH (pages_per_range = 32);

CREATE OR REPLACE FUNCTION orders.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := clock_timestamp();
    RETURN NEW;
END;
$$;

CREATE TRIGGER orders_set_updated_at
BEFORE UPDATE ON orders.orders
FOR EACH ROW EXECUTE FUNCTION orders.set_updated_at();

-- 原子扣库存：UPDATE 的行锁与 stock >= quantity 条件在同一条语句中完成。
CREATE OR REPLACE FUNCTION orders.reserve_stock(
    p_product_id bigint,
    p_quantity integer
)
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
    v_changed integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'quantity must be positive' USING ERRCODE = '22023';
    END IF;

    UPDATE orders.products
       SET stock = stock - p_quantity
     WHERE product_id = p_product_id
       AND stock >= p_quantity;

    GET DIAGNOSTICS v_changed = ROW_COUNT;
    RETURN v_changed = 1;
END;
$$;

-- 以幂等键把“扣库存 + 建订单 + 写事件”收进一个数据库事务边界。
CREATE OR REPLACE FUNCTION orders.place_order(
    p_tenant_id uuid,
    p_customer_id bigint,
    p_product_id bigint,
    p_quantity integer,
    p_idempotency_key text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = orders, pg_catalog
AS $$
DECLARE
    v_order_id bigint;
    v_price numeric(12, 2);
BEGIN
    SELECT order_id
      INTO v_order_id
      FROM orders.orders
     WHERE tenant_id = p_tenant_id
       AND idempotency_key = p_idempotency_key;
    IF v_order_id IS NOT NULL THEN
        RETURN v_order_id;
    END IF;

    SELECT price
      INTO v_price
      FROM orders.products
     WHERE product_id = p_product_id
       AND tenant_id = p_tenant_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'product does not belong to tenant' USING ERRCODE = '23503';
    END IF;

    IF NOT orders.reserve_stock(p_product_id, p_quantity) THEN
        RAISE EXCEPTION 'insufficient stock for product %', p_product_id
            USING ERRCODE = '23514';
    END IF;

    INSERT INTO orders.orders (
        tenant_id, customer_id, status, total_amount, idempotency_key
    ) VALUES (
        p_tenant_id, p_customer_id, 'paid', v_price * p_quantity, p_idempotency_key
    ) RETURNING order_id INTO v_order_id;

    INSERT INTO orders.order_items (order_id, product_id, quantity, unit_price)
    VALUES (v_order_id, p_product_id, p_quantity, v_price);

    INSERT INTO orders.order_events (order_id, event_type, payload)
    VALUES (
        v_order_id,
        'order.created',
        jsonb_build_object('idempotency_key', p_idempotency_key, 'quantity', p_quantity)
    );

    RETURN v_order_id;
END;
$$;

CREATE OR REPLACE VIEW orders.order_summary AS
SELECT
    o.order_id,
    o.tenant_id,
    c.email AS customer_email,
    o.status,
    o.total_amount,
    o.created_at,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'product_id', oi.product_id,
                'quantity', oi.quantity,
                'unit_price', oi.unit_price
            ) ORDER BY oi.product_id
        ) FILTER (WHERE oi.product_id IS NOT NULL),
        '[]'::jsonb
    ) AS items
FROM orders.orders AS o
JOIN orders.customers AS c ON c.customer_id = o.customer_id
LEFT JOIN orders.order_items AS oi ON oi.order_id = o.order_id
GROUP BY o.order_id, c.email;

CREATE OR REPLACE VIEW orders.low_stock AS
SELECT product_id, tenant_id, sku, product_name, stock
FROM orders.products
WHERE stock <= 10
ORDER BY stock, product_id;

CREATE MATERIALIZED VIEW orders.revenue_by_day AS
SELECT
    tenant_id,
    created_at::date AS order_day,
    count(*) AS order_count,
    sum(total_amount) AS revenue
FROM orders.orders
GROUP BY tenant_id, created_at::date;

CREATE UNIQUE INDEX revenue_by_day_tenant_day_idx
    ON orders.revenue_by_day (tenant_id, order_day);

CREATE OR REPLACE VIEW orders.top_customers AS
SELECT
    tenant_id,
    customer_id,
    sum(total_amount) AS gmv,
    dense_rank() OVER (
        PARTITION BY tenant_id
        ORDER BY sum(total_amount) DESC
    ) AS gmv_rank
FROM orders.orders
GROUP BY tenant_id, customer_id;

-- 租户角色用于验收 RLS；postgres 仍是运维 owner，便于备份与恢复。
ALTER TABLE orders.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders.orders FORCE ROW LEVEL SECURITY;
