#!/bin/bash
ES="https://localhost:9200"
PW="ESlearn2026"
C="curl.exe -s -k -u elastic:$PW"

echo "=== 版本 ==="
$C "$ES?filter_path=version.number"
echo ""
echo "=== 现有索引 ==="
$C "$ES/_cat/indices?v"
echo ""
echo "=== 集群健康 ==="
$C "$ES/_cluster/health?pretty"
echo ""
echo "=== DONE-L8-0 ==="
